### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by siriux** [YorickPeterse/inko#76]
Do you plan to add an open source license? If so, MIT + Apache (as Rust itself) would be great.

PS: Nice work !

**Comment by YorickPeterse** [comment]
@siriux The plan is to license it under the MPL 2.0 like my other projects, once I have a working compiler and a very basic standard library (basically enough to run something like hello world). For now there's no license since the project is nowhere near ready.

**Comment by siriux** [comment]
Thanks
